"$schema" = 'https://starship.rs/config-schema.json'


format = """
[╭╴](fg:arrow)\
$os\
$username\
[](bg:blue fg:dark_blue)\
$directory\
[](fg:blue bg:purple)\
$git_branch\
$git_status\
[](fg:purple bg:amber)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:amber bg:red)\
$docker_context\
$conda\
[](fg:red bg:base)\
$cmd_duration\
[ ](fg:base)
[╰─](fg:arrow)\
$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
white = "#F5EBD9"     # cor do texto
dark_blue = "#181825" # fundo principal
base = "#313244"
amber = "#df8e1d"     # fundo secundário (âmbar)
blue = "#04a5e5"      # azul
purple = "#8839ef"    # roxo
red = "#d20f39"       # vermelho
green = "#B9FBC0"     # verde
yellow = "#FAE3B0"    # amarelo

[os]
format = "[](dark_blue)[$symbol]($style)"
disabled = false
style = "bg:dark_blue fg:white"

[os.symbols]
Windows = "󰍲"
Ubuntu = " "
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:dark_blue fg:white"
style_root = "bg:dark_blue fg:white"
format = '[ ]($style)'

[directory]
style = "bold fg:dark_blue bg:blue"
format = "[ $path]($style)[ $read_only]($style)"
truncation_length = 2
truncation_symbol = "in "
read_only = "⛔"

[directory.substitutions]
"Documentos" = "󰈙 "
"Downloads" = " "
"Músicas" = "󰝚 "
"Imagens" = " "
"projects" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:purple"
format = '[[ $symbol $branch ](fg:white bg:purple)]($style)'

[git_status]
style = "bg:purple"
format = '[[($all_status$ahead_behind )](fg:white bg:purple)]($style)'

[nodejs]
symbol = ""
style = "bg:purple"
format = '[[ $symbol( $version) ](fg:dark_blue bg:amber)]($style)'

[c]
symbol = " "
style = "bg:purple"
format = '[[ $symbol( $version) ](fg:white bg:amber)]($style)'

[rust]
symbol = ""
style = "bg:purple"
format = '[[ $symbol( $version) ](fg:white bg:amber)]($style)'

[golang]
symbol = ""
style = "bg:purple"
format = '[[ $symbol( $version) ](fg:white bg:amber)]($style)'

[php]
symbol = ""
style = "bg:purple"
format = '[[ $symbol( $version) ](fg:white bg:amber)]($style)'

[java]
symbol = ""
style = "bg:purple"
format = '[[ $symbol( $version) ](fg:white bg:amber)]($style)'

[kotlin]
symbol = ""
style = "bg:purple"
format = '[[ $symbol( $version) ](fg:white bg:amber)]($style)'

[haskell]
symbol = ""
style = "bg:purple"
format = '[[ $symbol( $version) ](fg:white bg:amber)]($style)'

[python]
symbol = ""
style = "bg:purple"
format = '[[ $symbol( $version) ](fg:white bg:amber)]($style)'

[docker_context]
symbol = ""
style = "bg:amber"
format = '[[ $symbol( $context) ](fg:#83a598 bg:red)]($style)'

[conda]
style = "bg:amber"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:red)]($style)'

[time]
disabled = true
time_format = "%Hh%M"                                   # formato para exibir "22h30"
style = "bg:dark_blue"
format = '[[  $time ](fg:white bg:dark_blue)]($style)'

[cmd_duration]
min_time = 500
format = "[ took $duration](fg:white bold bg:base)"


[character]
disabled = false
success_symbol = '[ ❯](bold fg:green)'
error_symbol = '[ ✖](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:purple)'
vimcmd_replace_symbol = '[❮](bold fg:purple)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'
